### ISSUE TITLE
Various errors with example notebooks

### ISSUE THREAD

**Issue by thejasvibr** [mrilikecoding/StreamPoseML#19]
Hi,
This is in relation to https://github.com/openjournals/joss-reviews/issues/6392

It seems like the example notebooks haven't been tested on another system or environment with a 'clean' installation of the repo. 
Each of the notebooks I tried to run threw a variety of errors. 

I have raised multiple issues on the specifics, and this issue is a pointer on the need for an update + test on a clean installed system/environment,

**Comment by mrilikecoding** [comment]
Thank you, I appreciate it! I'll start working through the issues. Cheers.

**Comment by mrilikecoding** [comment]
Greetings - thank you for your patience. I have consolidated the example notebooks into this single notebook which should be more generalized and hopefully work out of the box: https://github.com/mrilikecoding/StreamPoseML/blob/main/stream_pose_ml/notebooks/example_usage.ipynb. Please let me know if you have issues running it.

I will close the other notebook related issues and leave this one open pending your review. If all looks good I'll close out this issue. Thanks!

**Comment by mrilikecoding** [comment]
Closing per https://github.com/openjournals/joss-reviews/issues/6392#issuecomment-2252332707
