### ISSUE TITLE
 unexpected keyword argument 'model_path'

### ISSUE THREAD

**Issue by thejasvibr** [mrilikecoding/StreamPoseML#21]
In the example notebook - while saving the model for the web application I get this error. I've run the notebook as of the latest commit on ```main``` (e3c14d...)

![image](https://github.com/mrilikecoding/StreamPoseML/assets/12443569/ab9003cc-0458-468b-a192-ed0173efa76c)

```
TypeError: ModelBuilder.save_model_and_datasets() got an unexpected keyword argument 'model_path'
```

This is in relation to the JOSS review process (https://github.com/openjournals/joss-reviews/issues/6392)

**Comment by mrilikecoding** [comment]
Thanks, will resolve and follow up

**Comment by mrilikecoding** [comment]
@thejasvibr my apologies for the long delay (eventful summer). I believe I have fixed this bug now. Please try again at your convenience -- will close with your confirmation this works. Cheers
