### ISSUE TITLE
'visual example' for step 7 of the schematic ('validate the model')

### ISSUE THREAD

**Issue by thejasvibr** [mrilikecoding/StreamPoseML#22]
Hi, 
The example notebook does a great job of showing the capabilities of the package. 
One important thing may be to show a new user a visual example (e.g. overlay of body key-points on a previously unseen video) of what comes out from the trained model in the example notebook. 
This is more likely to convince a first-time user who's not yet fully invested.

I see that there are already ROC curves etc. once the model is trained, but it might be useful to show the first-time casual user what the final outputs can actually look like? 

Something optional, and completely left to you of course. 

This is in relation to the JOSS review process (https://github.com/openjournals/joss-reviews/issues/6392)

**Comment by mrilikecoding** [comment]
Thanks, I'll give it some thought and follow up

**Comment by mrilikecoding** [comment]
I'm going to defer on this for now in the interest of time. If reviewers feel strongly happy to re=approach. Thanks
